services:
  pmm-filebeat:
    container_name: pmm-filebeat
    image: docker.elastic.co/beats/filebeat:6.6.0
    logging:
      options: 
        max-file: "2"
        max-size: "100m"
    restart: unless-stopped
    user: root
    volumes:
    - ./filebeat/configs:/usr/share/filebeat/configs
    - ./filebeat/data:/usr/share/filebeat/data
    - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    #- ./tomcat/logs:/usr/share/filebeat/logs/tomcat (map tomcat log directory to this location)
    #- ./nginx/logs:/usr/share/filebeat/logs/nginx
version: '3'
