FROM docker.elastic.co/logstash/logstash:6.6.2
RUN  /usr/share/logstash/bin/logstash-plugin install logstash-filter-elapsed
RUN  /usr/share/logstash/bin/logstash-plugin install logstash-filter-useragent

