FROM docker.elastic.co/elasticsearch/elasticsearch:6.6.2
#RUN /usr/share/elasticsearch/bin/elasticsearch-keystore create
#RUN echo test123 | /usr/share/elasticsearch/bin/elasticsearch-keystore add --stdin "bootstrap.password"
#RUN chown elasticsearch:root /usr/share/elasticsearch/config/elasticsearch.keystore


