#make sure to have owner and group of configs/*.yml file as root
#make sure to have the mode of filebeat.yml as 644 with owner as root.
#configs- contains yml files for input configurations. mysql-filebeat.yml specifies all tomcat log files. If a new harvester should be addded then it should be a new yml file in configs folder.
#data- it is mapped to docker so that the registry file generated by filebeat is made persistent on the host. So that the next time filebeat is run it starts from the last position onwards.
#logs - tomcat logs get mapped here .. When mysql is added we will map that separately under logs folder of /usr/share/filebeat/logs/ folder on filbeat docker. 
#docker run -d --name filebeat --user root -v /home/pmm/pmm-deploy/ELK/filebeat/configs:/usr/share/filebeat/configs -v /home/pmm/pmm-deploy/ELK/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml docker.elastic.co/beats/filebeat:6.6.0 
docker run --name filebeat -d --user root  --log-opt max-size=200m --log-opt max-file=20 -v /home/pmm/pmm-deploy/ELK/filebeat/configs:/usr/share/filebeat/configs -v /home/pmm/pmm-deploy/ELK/filebeat/data:/usr/share/filebeat/data -v /home/pmm/pmm-deploy/docker/tomcat/logs:/usr/share/filebeat/logs/test  -v /home/pmm/pmm-deploy/ELK/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml docker.elastic.co/beats/filebeat:6.6.0 
#docker run -d --name filebeat --user root -p 5044:5044 -v /home/pmm/pmm-deploy/ELK/filebeat/configs:/usr/share/filebeat/configs -v /home/pmm/pmm-deploy/docker/tomcat/logs:/usr/share/filebeat/logs/test  -v /home/pmm/pmm-deploy/ELK/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml docker.elastic.co/beats/filebeat:6.6.0  

